CREATE DATABASE PizzaChainDB;
USE PizzaChainDB;

CREATE TABLE STORE (
    StoreID INT PRIMARY KEY AUTO_INCREMENT,
    Phone VARCHAR(20) NOT NULL UNIQUE,
    City VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEE (
    SSN CHAR(11) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    HireDate DATE NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Wage DECIMAL(8,2) NOT NULL CHECK (Wage > 0),
    Phone VARCHAR(20),
    StoreID INT NOT NULL,
    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);

CREATE TABLE INVENTORY_ITEM (
    InvItemID INT PRIMARY KEY AUTO_INCREMENT,
    ItemName VARCHAR(100) NOT NULL,
    ItemType VARCHAR(50) NOT NULL,
    Unit VARCHAR(50) NOT NULL
);

CREATE TABLE STORE_INVENTORY (
    StoreID INT NOT NULL,
    InvItemID INT NOT NULL,
    QuantityOnHand INT NOT NULL CHECK (QuantityOnHand >= 0),
    ReorderLevel INT NOT NULL CHECK (ReorderLevel >= 0),
    PRIMARY KEY (StoreID, InvItemID),
    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID),
    FOREIGN KEY (InvItemID) REFERENCES INVENTORY_ITEM(InvItemID)
);

CREATE TABLE PRODUCT (
    ProductID INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(100) NOT NULL,
    Category VARCHAR(50),
    Price DECIMAL(8,2) NOT NULL CHECK (Price > 0)
);

CREATE TABLE RECIPE (
    ProductID INT NOT NULL,
    InvItemID INT NOT NULL,
    QuantityRequired DECIMAL(8,2) NOT NULL CHECK (QuantityRequired > 0),
    UnitAmount VARCHAR(50) NOT NULL,
    PRIMARY KEY (ProductID, InvItemID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    FOREIGN KEY (InvItemID) REFERENCES INVENTORY_ITEM(InvItemID)
);

CREATE TABLE ORDERS (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    OrderDateTime DATETIME NOT NULL,
    Total DECIMAL(10,2) NOT NULL CHECK (Total >= 0),
    Status VARCHAR(50) NOT NULL,
    CustomerID INT NOT NULL,
    StoreID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID)
);

CREATE TABLE DINING_ORDER (
    OrderID INT PRIMARY KEY,
    PartySize INT NOT NULL CHECK (PartySize > 0),
    TableNumber INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

CREATE TABLE TAKEOUT_ORDER (
    OrderID INT PRIMARY KEY,
    PickupTime DATETIME NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

CREATE TABLE DELIVERY_ORDER (
    OrderID INT PRIMARY KEY,
    DeliveryAddress VARCHAR(255) NOT NULL,
    EstimatedArrivalTime DATETIME NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

CREATE TABLE ORDER_ITEM (
    OrderID INT NOT NULL,
    LineNumber INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    ItemPrice DECIMAL(8,2) NOT NULL CHECK (ItemPrice > 0),
    SpecialInstructions VARCHAR(255),
    PRIMARY KEY (OrderID, LineNumber),
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE PAYMENT_METHOD (
    PaymentMethodID INT PRIMARY KEY AUTO_INCREMENT,
    PaymentType VARCHAR(50) NOT NULL,
    LastFourDigits CHAR(4) NOT NULL,
    CustomerID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE PAYMENT (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    Amount DECIMAL(10,2) NOT NULL CHECK (Amount >= 0),
    PaymentDateTime DATETIME NOT NULL,
    OrderID INT NOT NULL UNIQUE,
    PaymentMethodID INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
    FOREIGN KEY (PaymentMethodID) REFERENCES PAYMENT_METHOD(PaymentMethodID)
);